### ISSUE TITLE
No hint path defined for [google2fa]

### ISSUE THREAD

**Issue by mattiasgeniar** [cretueusebiu/laravel-spark-google2fa#12]
After following your installations steps, I get the following error message.

```
No hint path defined for [google2fa]. (View: resources/views/vendor/spark/settings/security/enable-two-factor-auth.blade.php) (View: resources/views/vendor/spark/settings/security/enable-two-factor-auth.blade.php) (View: resources/views/vendor/spark/settings/security/enable-two-factor-auth.blade.php)
```

The only clue I can find, is that the last command that I should've run, ```npm run dev```,  failed on me;

```
$ npm run dev
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log
```

Any clues as to where I could go looking?

**Comment by cretueusebiu** [comment]
Make sure you've added the service provider `Eusebiu\LaravelSparkGoogle2FA\Google2FAServiceProvider::class` in `config/app.php`. Also run `php artisan config:clear` to clear the cached config.

As for the `npm run dev` command, do you have the `dev` script in your package.json ?

**Comment by mattiasgeniar** [comment]
The ```php artisan config:clear``` fixed it, thank you for your quick reply!

I don't have the ```dev``` script, and I'll be honest that I don't _really_ know why I'd need it? Feel free to go ahead and close the issue, this was resolved with the ```config:clear```.

**Comment by cretueusebiu** [comment]
Well, how do you compile the JavaScript then ? By default Spark comes with that command.
