### ISSUE TITLE
The code is invalid

### ISSUE THREAD

**Issue by fballiano** [cretueusebiu/laravel-spark-google2fa#29]
Hi, I've a Spark 7.1.4 project and I successfully (almost) installed and configured your module (thanks, it's great funcionality). I can add the project on Google Authenticator but when I enter the code to confirm the 2fa activation the code is not valid

<img width="489" alt="Schermata 2020-01-20 alle 18 25 15" src="https://user-images.githubusercontent.com/909743/72749531-39e8d880-3bb2-11ea-97f9-59a7bbb92447.png">

Do you have any idea what may cause this kind of behaviour?

Thanks a lot!

**Comment by fballiano** [comment]
ok I kinda found out what's going on... if I validate an OTP code in the last few seconds (before it expired) it gets validated correctly, but not before...

that's really weird, any idea?

**Comment by thomaswardiii** [comment]
If it's a timing issue, make sure the server that is generating and validating this code is synchronized with time correctly. Not just to the minute, to the second. The codes only work for 30 seconds, so if you're about 25 seconds ahead/behind, it will screw up your ability to use that code during the window.

**Comment by fballiano** [comment]
Thanks so much!

**Comment by thomaswardiii** [comment]
No problem. I highly recommend ALL servers on the internet have ntp synchronization
