### ISSUE TITLE
[PROPOSAL] Allow enter key to submit verify qr code form

### ISSUE THREAD

**Issue by arenowebdev** [cretueusebiu/laravel-spark-google2fa#5]
Great work on this and very quickly I may add too!

Just thought I would throw this out there and would do a PR if you're willing to allow me to allow the enter key to submit the verify qr code form after the initial setup of two factor auth for the user...

With your blessing, the PR should take literally a minute ;)

Thanks!

**Comment by cretueusebiu** [comment]
Sure!

**Comment by arenowebdev** [comment]
PR #6 does this...closing this issue...
