### ISSUE TITLE
Invalid Barcode caused by spaces in $details['vendor']

### ISSUE THREAD

**Issue by securit** [cretueusebiu/laravel-spark-google2fa#7]
Hi, 

You need to make your getQrUrl function URL safe by encoding it as spaces or safe characters in the $details['vendor'] string can cause the QR code generation to fail.

Modify line 53 of TwoFactorAuthController to URLencode the vendor details as follows:

`$company = isset(Engagement::$details['vendor']) ? urlencode(Engagement::$details['vendor']) : url()->to('/');
`

That will resolve this bug

**Comment by cretueusebiu** [comment]
Fixed https://github.com/cretueusebiu/laravel-spark-google2fa/commit/e5bd639a1e61e72ae22965acd92644157f276a7b
